use_half: False

work_dir: ./results/LTX/
data_path: ./results/LTX/lmdb/  # path/to/saved/lmdb
data_meta: ./results/LTX/meta/train.json  #meta/train.json
content_reference_json: ./meta/cr_mapping.json
content_font: "common_words" #content file name
language: "chn"

C: 32
input_size: 128
num_heads: 8
kshot: 3

g_args:
  comp_enc:
    norm: "in"
    activ: relu
  dec:
    norm: "in"
    activ: relu
    out: sigmoid
  content_enc:
    C_out: 256
    content_sigmoid: False
    
d_args:
  w_norm: spectral
  activ: relu
  gap_activ: relu
  res_scale_var: False

# losses
pixel_loss_type: l1
pixel_w: 0.1
gan_w: 1.0

init: xavier
dset_aug:
  normalize: True
  
cv_n_unis: 30
cv_n_fonts: 10

batch_size: 32
n_workers: 6
iter: 600000 #10epoch (~60k data)
g_lr: 2e-4
d_lr: 6e-4 
step_size: 3000 #change lr for each 10k iter
gamma: 0.95
overwrite: False
adam_betas: [0.0, 0.9]

# cv_n_unis: 15 # 30
# cv_n_fonts: 9 # 10

print_freq: 1000
val_freq: 1000
save_freq: 10000
tb_freq: 100
